from __future__ import annotations

"""로컬 HTML 리포트 공유 API 서버.

이 파일은 Langflow에서 생성한 HTML 문자열을 로컬 PC의 파일 저장소에 저장하고,
사용자가 내려받을 수 있는 URL을 만들어 주는 작은 FastAPI 서버입니다.

전체 흐름은 다음과 같습니다.
1. Langflow의 `05-2 공유 링크 출력` 노드가 `/reports`로 HTML을 POST합니다.
2. 서버는 HTML 파일과 메타데이터 JSON 파일을 `storage/reports` 폴더에 저장합니다.
3. 응답으로 보기 URL, 다운로드 URL, 만료 시간을 돌려줍니다.
4. 사용자가 링크를 열면 서버가 만료 여부를 먼저 확인한 뒤 HTML을 반환합니다.
5. 만료된 리포트는 접근 시점 또는 서버 시작/새 리포트 생성 시점에 자동 삭제됩니다.
"""

import hashlib
import json
import re
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any
from urllib.parse import quote

from fastapi import FastAPI, HTTPException, Query, Response
from pydantic import BaseModel, Field


# 여기만 바꾸면 별도 .env 파일 없이 실행 설정을 조정할 수 있습니다.
SERVER_HOST = "127.0.0.1"
SERVER_PORT = 8010
BASE_URL = f"http://{SERVER_HOST}:{SERVER_PORT}"
STORAGE_DIR = Path(__file__).resolve().parent / "storage"
DEFAULT_TTL_HOURS = 24
MAX_TTL_HOURS = 24 * 7
MAX_HTML_BYTES = 10 * 1024 * 1024
MAX_STORAGE_BYTES = 512 * 1024 * 1024
USE_ACCESS_TOKEN = False


class DatasetRef(BaseModel):
    """리포트에 사용된 데이터셋 요약 정보.

    실제 데이터 전체를 다시 저장하기보다, 어떤 데이터셋을 바탕으로 만들었는지
    식별자와 컬럼/row 수 정도만 메타데이터에 남기기 위한 모델입니다.
    """

    dataset_id: str = ""
    label: str = ""
    data_ref: dict[str, Any] = Field(default_factory=dict)
    columns: list[str] = Field(default_factory=list)
    row_count: int = 0


class CreateReportRequest(BaseModel):
    """`POST /reports` 요청 바디 형식.

    Langflow가 만든 최종 HTML 문자열과 제목, 질문, 유효시간 등을 받아서
    서버가 저장할 파일과 다운로드 링크를 만들 수 있게 합니다.
    """

    html: str = Field(..., description="Final HTML string generated by html_report_flow.")
    title: str = "HTML Report"
    question: str = ""
    view_request: str = ""
    available_datasets: list[DatasetRef] = Field(default_factory=list)
    report_plan: dict[str, Any] = Field(default_factory=dict)
    ttl_hours: int | None = Field(default=None, ge=1)
    filename_hint: str = "report"


class CreateReportResponse(BaseModel):
    """`POST /reports`가 성공했을 때 Langflow로 돌려주는 응답 형식."""

    report_id: str
    title: str
    view_url: str
    download_url: str
    expires_at: str
    ttl_hours: int


app = FastAPI(title="Local HTML Report API", version="0.2.0")


@app.on_event("startup")
def startup() -> None:
    """서버가 켜질 때 저장 폴더를 준비하고 오래된 리포트를 정리합니다."""

    _reports_dir().mkdir(parents=True, exist_ok=True)
    _cleanup_expired_reports()
    _enforce_storage_limit()


@app.get("/")
def alive() -> Response:
    """서버가 살아 있는지 간단히 확인하는 health-check 주소입니다."""

    return Response(content="alive!", media_type="text/plain")


@app.get("/api/admin/appReady")
def app_ready() -> Response:
    """일부 배포 환경에서 appReady 확인용으로 호출할 수 있는 health-check 주소입니다."""

    return Response(content="alive!", media_type="text/plain")


@app.post("/reports", response_model=CreateReportResponse)
def create_report(request: CreateReportRequest) -> CreateReportResponse:
    """HTML 리포트를 저장하고 공유 링크 정보를 생성합니다.

    초보자용 흐름 설명:
    - `request.html`이 실제 HTML 원문입니다.
    - HTML이 비어 있거나 너무 크면 저장하지 않고 오류를 냅니다.
    - `ttl_hours`를 이용해 만료 시간을 계산합니다.
    - `{report_id}.html`에는 HTML 원문을, `{report_id}.json`에는 제목/만료시간 같은
      메타데이터를 저장합니다.
    - 저장 후에는 이미 만료된 과거 파일과 용량 초과 파일을 정리합니다.
    """

    html_bytes = request.html.encode("utf-8")
    if not request.html.strip():
        raise HTTPException(status_code=400, detail="html is empty")
    if len(html_bytes) > MAX_HTML_BYTES:
        raise HTTPException(status_code=413, detail=f"html is too large. max_bytes={MAX_HTML_BYTES}")

    now = datetime.now(timezone.utc)
    ttl_hours = _effective_ttl_hours(request.ttl_hours)
    expires_at = now + timedelta(hours=ttl_hours)
    report_id = _new_report_id()
    filename = _safe_html_filename(request.filename_hint or request.title or report_id)
    token = uuid.uuid4().hex if USE_ACCESS_TOKEN else ""

    # HTML 파일 옆에 저장할 JSON 메타데이터입니다.
    # 만료 여부를 판단할 때는 여기의 `expires_at` 값을 다시 읽습니다.
    doc = {
        "report_id": report_id,
        "title": request.title or "HTML Report",
        "question": request.question,
        "view_request": request.view_request,
        "available_datasets": [item.model_dump() for item in request.available_datasets],
        "report_plan": request.report_plan,
        "html_bytes": len(html_bytes),
        "download_filename": filename,
        "created_at": _to_iso(now),
        "expires_at": _to_iso(expires_at),
        "ttl_hours": ttl_hours,
    }
    if token:
        # 토큰을 사용할 때도 원문 토큰은 저장하지 않고 해시만 저장합니다.
        doc["access_token_sha256"] = _hash_token(token)

    # 파일 저장은 HTML과 JSON을 분리합니다.
    # 이렇게 하면 다운로드는 HTML만 읽고, 만료/제목 확인은 JSON만 읽을 수 있습니다.
    _write_text(_html_path(report_id), request.html)
    _write_json(_meta_path(report_id), doc)
    _cleanup_expired_reports()
    _enforce_storage_limit()
    return _response_from_doc(doc, token=token)


@app.get("/reports/view/{report_id}")
def view_report(report_id: str, token: str = Query(default="")) -> Response:
    """브라우저에서 HTML을 바로 열어볼 수 있게 `text/html`로 반환합니다."""

    doc = _load_active_report(report_id, token)
    return Response(content=_read_html(report_id), media_type="text/html; charset=utf-8")


@app.get("/reports/download/{report_id}")
def download_report(report_id: str, token: str = Query(default="")) -> Response:
    """HTML 파일을 다운로드 파일로 내려줍니다."""

    doc = _load_active_report(report_id, token)
    filename = _safe_html_filename(doc.get("download_filename") or doc.get("title") or report_id)
    return Response(
        content=_read_html(report_id).encode("utf-8"),
        media_type="application/octet-stream",
        headers={"Content-Disposition": _content_disposition(filename)},
    )


@app.get("/view/{report_id}")
def view_report_short(report_id: str, token: str = Query(default="")) -> Response:
    """짧은 보기 URL입니다. 내부적으로 `/reports/view/{report_id}`와 같은 동작을 합니다."""

    return view_report(report_id, token)


@app.get("/down/{report_id}")
def download_report_short(report_id: str, token: str = Query(default="")) -> Response:
    """짧은 다운로드 URL입니다. 내부적으로 `/reports/download/{report_id}`와 같은 동작을 합니다."""

    return download_report(report_id, token)


@app.delete("/reports/{report_id}")
def delete_report(report_id: str, token: str = Query(default="")) -> dict[str, Any]:
    """특정 리포트를 수동으로 삭제합니다."""

    doc = _load_active_report(report_id, token)
    _delete_report_files(str(doc["report_id"]))
    return {"status": "ok", "deleted": True, "report_id": report_id}


def _load_active_report(report_id: str, token: str = "") -> dict[str, Any]:
    """리포트를 읽기 전에 ID, 존재 여부, 만료 여부, 토큰을 검사합니다.

    이 함수가 보기/다운로드/삭제 API 앞단의 공통 문지기 역할을 합니다.
    만료된 리포트라면 바로 파일을 삭제하고 HTTP 410 Gone 오류를 냅니다.
    """

    if not _valid_report_id(report_id):
        raise HTTPException(status_code=400, detail="invalid report_id")
    doc = _read_json(_meta_path(report_id))
    if not doc or not _html_path(report_id).exists():
        raise HTTPException(status_code=404, detail="report not found")
    expires_at = _parse_datetime(doc.get("expires_at"))
    if expires_at and expires_at <= datetime.now(timezone.utc):
        # 만료된 링크를 누른 순간에도 정리가 일어나도록 합니다.
        _delete_report_files(report_id)
        raise HTTPException(status_code=410, detail="report expired")
    expected_hash = doc.get("access_token_sha256")
    if expected_hash and _hash_token(token) != expected_hash:
        raise HTTPException(status_code=403, detail="invalid access token")
    return doc


def _response_from_doc(doc: dict[str, Any], token: str = "") -> CreateReportResponse:
    """저장된 메타데이터를 Langflow가 쓰기 쉬운 응답 모델로 바꿉니다."""

    base_url = BASE_URL.rstrip("/")
    report_id = str(doc["report_id"])
    suffix = f"?token={token}" if token else ""
    return CreateReportResponse(
        report_id=report_id,
        title=str(doc.get("title") or "HTML Report"),
        view_url=f"{base_url}/reports/view/{report_id}{suffix}",
        download_url=f"{base_url}/reports/download/{report_id}{suffix}",
        expires_at=str(doc.get("expires_at") or ""),
        ttl_hours=int(doc.get("ttl_hours") or DEFAULT_TTL_HOURS),
    )


def _reports_dir() -> Path:
    """HTML/JSON 리포트 파일이 실제로 저장되는 폴더 경로를 반환합니다."""

    return _storage_dir() / "reports"


def _storage_dir() -> Path:
    """저장소 루트 경로를 절대 경로로 반환합니다."""

    return STORAGE_DIR.resolve()


def _html_path(report_id: str) -> Path:
    """리포트 ID에 해당하는 HTML 파일 경로를 만듭니다."""

    return _safe_child_path(_reports_dir(), f"{report_id}.html")


def _meta_path(report_id: str) -> Path:
    """리포트 ID에 해당하는 JSON 메타데이터 파일 경로를 만듭니다."""

    return _safe_child_path(_reports_dir(), f"{report_id}.json")


def _safe_child_path(base: Path, filename: str) -> Path:
    """저장 폴더 밖의 파일에 접근하지 못하게 경로를 검증합니다.

    사용자가 URL에 `../` 같은 값을 넣어 다른 폴더를 읽는 일을 막기 위한
    기본적인 path traversal 방어 코드입니다.
    """

    base_resolved = base.resolve()
    path = (base_resolved / filename).resolve()
    if not str(path).startswith(str(base_resolved)):
        raise HTTPException(status_code=400, detail="invalid path")
    return path


def _write_text(path: Path, text: str) -> None:
    """텍스트 파일을 안전하게 저장합니다.

    바로 원본 파일에 쓰지 않고 `.tmp` 파일에 먼저 쓴 뒤 교체합니다.
    저장 중 오류가 나도 기존 파일이 반쯤 깨지는 상황을 줄이기 위한 방식입니다.
    """

    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def _write_json(path: Path, value: dict[str, Any]) -> None:
    """딕셔너리를 사람이 읽기 쉬운 JSON 파일로 저장합니다."""

    _write_text(path, json.dumps(value, ensure_ascii=False, indent=2, default=str))


def _read_json(path: Path) -> dict[str, Any]:
    """JSON 파일을 읽어 딕셔너리로 반환합니다.

    파일이 없거나 JSON 형식이 깨져 있으면 서버가 죽지 않도록 빈 딕셔너리를 반환합니다.
    """

    try:
        parsed = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}
    except Exception:
        return {}
    return parsed if isinstance(parsed, dict) else {}


def _read_html(report_id: str) -> str:
    """리포트 ID에 해당하는 HTML 원문을 읽습니다."""

    try:
        return _html_path(report_id).read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise HTTPException(status_code=404, detail="report html not found") from exc


def _cleanup_expired_reports() -> None:
    """저장 폴더를 훑어 만료 시간이 지난 리포트를 삭제합니다.

    이 함수는 서버 시작 시점과 새 리포트 생성 시점에 호출됩니다.
    초 단위로 계속 도는 스케줄러는 아니므로, 만료 직후 즉시 삭제되는 구조는 아닙니다.
    """

    now = datetime.now(timezone.utc)
    for meta_path in _reports_dir().glob("*.json"):
        doc = _read_json(meta_path)
        report_id = str(doc.get("report_id") or meta_path.stem)
        expires_at = _parse_datetime(doc.get("expires_at"))
        if expires_at and expires_at <= now:
            _delete_report_files(report_id)


def _enforce_storage_limit() -> None:
    """저장소 전체 용량이 제한을 넘으면 오래된 리포트부터 삭제합니다.

    TTL 만료와는 별개의 안전장치입니다. 여러 사람이 테스트하면서 파일이 많이 쌓일 때
    로컬 디스크가 과하게 사용되지 않도록 막습니다.
    """

    files = [path for path in _reports_dir().glob("*") if path.is_file()]
    total = sum(path.stat().st_size for path in files if path.exists())
    if total <= MAX_STORAGE_BYTES:
        return
    meta_files = sorted(_reports_dir().glob("*.json"), key=lambda path: path.stat().st_mtime)
    for meta_path in meta_files:
        doc = _read_json(meta_path)
        _delete_report_files(str(doc.get("report_id") or meta_path.stem))
        files = [path for path in _reports_dir().glob("*") if path.is_file()]
        total = sum(path.stat().st_size for path in files if path.exists())
        if total <= MAX_STORAGE_BYTES:
            break


def _delete_report_files(report_id: str) -> None:
    """하나의 리포트에 연결된 HTML 파일과 JSON 메타데이터 파일을 함께 삭제합니다."""

    if not _valid_report_id(report_id):
        return
    for path in (_html_path(report_id), _meta_path(report_id)):
        try:
            path.unlink()
        except FileNotFoundError:
            pass


def _effective_ttl_hours(value: int | None) -> int:
    """입력받은 유효시간을 최소 1시간, 최대 `MAX_TTL_HOURS` 범위로 보정합니다."""

    ttl = value if value is not None else DEFAULT_TTL_HOURS
    return max(1, min(int(ttl), MAX_TTL_HOURS))


def _new_report_id() -> str:
    """현재 UTC 시각과 UUID를 합쳐 충돌 가능성이 낮은 리포트 ID를 만듭니다."""

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    return f"{timestamp}_{uuid.uuid4().hex}"


def _valid_report_id(report_id: str) -> bool:
    """리포트 ID가 서버가 만든 형식인지 확인합니다."""

    return bool(re.fullmatch(r"[0-9]{14}_[a-f0-9]{32}", str(report_id or "")))


def _safe_html_filename(value: Any) -> str:
    """다운로드 파일명으로 쓰기 안전한 `.html` 이름을 만듭니다.

    예전 로직은 영문/숫자만 허용해서 `공정별_WIP_리포트` 같은 한글 이름이
    전부 `_`로 바뀐 뒤 사라졌습니다. 여기서는 한글/영문/숫자와 일부 안전한
    구분자만 남기고, Windows 파일명에 문제가 되는 문자만 제거합니다.
    """

    raw = str(value or "report").strip()
    raw = re.sub(r"\.html?$", "", raw, flags=re.I)
    raw = re.sub(r"[\\/:*?\"<>|\r\n\t]+", "_", raw)
    raw = re.sub(r"\s+", "_", raw)
    raw = "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in raw)
    raw = raw.strip("._-") or "report"
    return f"{raw[:80]}.html"


def _content_disposition(filename: str) -> str:
    """브라우저가 한글 다운로드 파일명을 인식하도록 헤더 값을 만듭니다.

    `filename`은 오래된 브라우저용 ASCII fallback이고, `filename*`는 RFC 5987
    방식의 UTF-8 파일명입니다. 최신 Edge/Chrome은 `filename*` 값을 우선 사용합니다.
    """

    safe_filename = _safe_html_filename(filename)
    fallback = _ascii_filename_fallback(safe_filename)
    encoded = quote(safe_filename, safe="")
    return f"attachment; filename=\"{fallback}\"; filename*=UTF-8''{encoded}"


def _ascii_filename_fallback(filename: str) -> str:
    """한글 파일명을 지원하지 않는 환경을 위한 영문 fallback 파일명을 만듭니다."""

    ascii_name = str(filename or "report.html").encode("ascii", errors="ignore").decode("ascii")
    ascii_name = re.sub(r"[^A-Za-z0-9._-]+", "_", ascii_name)
    ascii_name = re.sub(r"\.html?$", "", ascii_name, flags=re.I)
    ascii_name = ascii_name.strip("._-") or "report"
    return f"{ascii_name[:80]}.html"


def _hash_token(token: str) -> str:
    """접근 토큰을 그대로 저장하지 않기 위해 SHA-256 해시로 변환합니다."""

    return hashlib.sha256(str(token or "").encode("utf-8")).hexdigest()


def _to_iso(value: datetime) -> str:
    """datetime 값을 UTC ISO 문자열로 변환합니다."""

    return value.astimezone(timezone.utc).isoformat()


def _parse_datetime(value: Any) -> datetime | None:
    """문자열로 저장된 시간을 UTC datetime으로 다시 변환합니다."""

    text = str(value or "").strip()
    if not text:
        return None
    try:
        parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
    except Exception:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def run_server() -> None:
    """이 파일을 직접 실행했을 때 uvicorn으로 FastAPI 서버를 띄웁니다."""

    import uvicorn

    print(f"Local HTML Report API: {BASE_URL}")
    print(f"Storage folder: {_reports_dir()}")
    uvicorn.run(app, host=SERVER_HOST, port=SERVER_PORT)


if __name__ == "__main__":
    run_server()
